country_ids = {
    'France': 'FR',
    'Greece': 'GR',
    'Turkey': 'TR',
    'Portugal': 'PT',
    'Spain': 'ES',
    'Switzerland': 'CH',
    'Italy': 'IT',
    'Germany': 'DE',
    'Belgium': 'BE',
    'Netherlands': 'NL',
    'Luxembourg': 'LU',
    'Serbia': 'RS',
    'North Macedonia': 'MK',
    'Albania': 'AL',
    'Montenegro': 'ME',
    'Bosnia and Herzegovina': 'BA',
    'Croatia': 'HR',
    'Slovenia': 'SI',
    'Hungary': 'HU',
    'Austria': 'AT',
    'Slovakia': 'SK',
    'Czechia': 'CZ',
    'Romania': 'RO',
    'Bulgaria': 'BG',
    'Malta': 'MT',
    'Liechtenstein': 'LI',
    'Cyprus': 'CY',
    'United Kingdom': 'UK',
    'Ireland': 'IE',
    'Iceland': 'IS',
    'Norway': 'NO',
    'Sweden': 'SE',
    'Finland': 'FI',
    'Lithuania': 'LT',
    'Latvia': 'LV',
    'Estonia': 'EE',
    'Belarus': 'BY',
    'Ukraine': 'UA',
    'Russian Federation': 'RU',
    'Denmark': 'DK'
}